server:
  port: 8080
# Setting
spring:
  application:
    name: thedots
  datasource:
    # H2
    url: jdbc:h2:mem:thedots
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  # JPA
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

springdoc:
  swagger-ui:
    path: /thedots/swagger.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /reservations/**

logging:
  level:
    com.ch.user: debug
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

# JPA Query log
decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true